#! /bin/sh

rofi_cmd() {
	rofi -dmenu \
		-theme ~/.config/bspwm/rofi/configs/power.rasi
}

chosen=$(printf "\n\n" | rofi_cmd)

case "$chosen" in
	"") systemctl poweroff ;;
	"") systemctl reboot ;;
	"") bspc quit ;;
	*) exit 1 ;;
esac
