#! /bin/bash

pgrep -x sxhkd > /dev/null || sxhkd -c .config/bspwm/sxhkdrc &
$HOME/.config/bspwm/polybar/launch.sh &
pgrep -x dunst > /dev/null || dunst -config .config/bspwm/dunstrc &
pgrep -x picom > /dev/null || picom --config .config/bspwm/picom.conf &
xsetroot -cursor_name left_ptr &
feh --bg-fill /usr/share/backgrounds/wall.jpg &
xset r rate 215 50 &
$HOME/.local/bin/greenclip daemon &
xfce4-power-manager &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
firewall-applet &
pgrep -x pipewire > /dev/null || pipewire &
pgrep -x pipewire-pulse > /dev/null || pipewire-pulse &
pgrep -x wireplumber > /dev/null || wireplumber &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         0
bspc config window_gap           8
bspc config split_ratio          0.5
bspc config focus_follows_pointer true
bspc config presel_feedback_color "#d4be98"

bspc rule -a feh state=fullscreen
bspc rule -a Zathura state=fullscreen
